services:
  postgres:
    image: postgres:15-alpine
    container_name: hackaton-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: hackaton-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring": {
            "datasource": {
              "url": "jdbc:postgresql://postgres:5432/${DB_NAME}",
              "username": "${DB_USERNAME}",
              "password": "${DB_PASSWORD}"
            },
            "liquibase": {
              "enabled": ${LIQUIBASE_ENABLED}
            },
            "security": {
              "user": {
                "name": "${SECURITY_USER_NAME}",
                "password": "${SECURITY_USER_PASSWORD}"
              }
            },
            "mail": {
              "host": "${MAIL_HOST}",
              "port": ${MAIL_PORT},
              "username": "${MAIL_USERNAME}",
              "password": "${MAIL_PASSWORD}"
            }
          },
          "cors": {
            "allowed-origins": "${ALLOWED_ORIGINS}"
          }
        }

volumes:
  postgres_data: