spring.application.name=hackaton

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/itupolev

server.port=8080

spring.liquibase.change-log=classpath:migrations/master.xml
spring.liquibase.enabled=true